name: PR Build
on:
  push:
    branches:
      - main
      - java8
  pull_request:
    types: [opened, edited, reopened, synchronize]
    
env:
  JABBA_INDEX: 'https://github.com/typelevel/jdk-index/raw/main/index.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: temurin@17
      - run: sbt commitCheck
