name: PR Build
on:
  push:
    branches:
      - main
      - java8
  pull_request:
    branches:
      - main
      - java8
env:
  JABBA_INDEX: 'https://github.com/typelevel/jdk-index/raw/main/index.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: adoptium@17
      - run: sbt commitCheck
        env:
          TEST_WEAVER: false
